const VERBS = [
  { kanji: "食べます", kana: "たべます", no: "å spise" },
  { kanji: "飲みます", kana: "のみます", no: "å drikke" },
  { kanji: "行きます", kana: "いきます", no: "å dra (til et sted)" },
  { kanji: "来ます", kana: "きます", no: "å komme" },
  { kanji: "帰ります", kana: "かえります", no: "å dra hjem" },
  { kanji: "見ます", kana: "みます", no: "å se" },
  { kanji: "聞きます", kana: "ききます", no: "å høre / lytte" },
  { kanji: "読みます", kana: "よみます", no: "å lese" },
  { kanji: "書きます", kana: "かきます", no: "å skrive" },
  { kanji: "話します", kana: "はなします", no: "å snakke" },
  { kanji: "言います", kana: "いいます", no: "å si" },
  { kanji: "買います", kana: "かいます", no: "å kjøpe" },
  { kanji: "会います", kana: "あいます", no: "å møte" },
  { kanji: "待ちます", kana: "まちます", no: "å vente" },
  { kanji: "立ちます", kana: "たちます", no: "å reise seg / stå" },
  { kanji: "座ります", kana: "すわります", no: "å sette seg" },
  { kanji: "起きます", kana: "おきます", no: "å våkne / stå opp" },
  { kanji: "寝ます", kana: "ねます", no: "å sove / legge seg" },
  { kanji: "働きます", kana: "はたらきます", no: "å jobbe" },
  { kanji: "休みます", kana: "やすみます", no: "å hvile / ta fri" },
  { kanji: "作ります", kana: "つくります", no: "å lage" },
  { kanji: "使います", kana: "つかいます", no: "å bruke" },
  { kanji: "開けます", kana: "あけます", no: "å åpne" },
  { kanji: "閉めます", kana: "しめます", no: "å lukke" },
  { kanji: "入ります", kana: "はいります", no: "å gå inn" },
  { kanji: "出ます", kana: "でます", no: "å gå ut" },
  { kanji: "泳ぎます", kana: "およぎます", no: "å svømme" },
  { kanji: "走ります", kana: "はしります", no: "å løpe" },
  { kanji: "歩きます", kana: "あるきます", no: "å gå (til fots)" },
  { kanji: "教えます", kana: "おしえます", no: "å undervise / lære bort" },
  { kanji: "習います", kana: "ならいます", no: "å lære (av noen)" },
  { kanji: "勉強します", kana: "べんきょうします", no: "å studere" },
  { kanji: "料理します", kana: "りょうりします", no: "å lage mat" },
  { kanji: "掃除します", kana: "そうじします", no: "å gjøre rent" },
  { kanji: "洗濯します", kana: "せんたくします", no: "å vaske klær" },
  { kanji: "買い物します", kana: "かいものします", no: "å handle" },
  { kanji: "電話します", kana: "でんわします", no: "å ringe" },
  { kanji: "運転します", kana: "うんてんします", no: "å kjøre (bil)" },
  { kanji: "旅行します", kana: "りょこうします", no: "å reise (på tur)" },
  { kanji: "散歩します", kana: "さんぽします", no: "å gå tur" },
  { kanji: null, kana: "します", no: "å gjøre" },
  { kanji: null, kana: "あります", no: "å finnes (ting)" },
  { kanji: null, kana: "います", no: "å være (levende vesener)" },
  { kanji: "着ます", kana: "きます", no: "å ha på seg (overdel)" },
  { kanji: null, kana: "はきます", no: "å ha på seg (bukse/sko)" },
  { kanji: null, kana: "かぶります", no: "å ha på seg (hodeplagg)" },
  { kanji: "脱ぎます", kana: "ぬぎます", no: "å ta av seg (klær)" },
  { kanji: "住みます", kana: "すみます", no: "å bo" },
  { kanji: "思います", kana: "おもいます", no: "å synes / tro" },
  { kanji: "泣きます", kana: "なきます", no: "å gråte" },
  { kanji: "笑います", kana: "わらいます", no: "å le" },
  { kanji: "歌います", kana: "うたいます", no: "å synge" },
  { kanji: "踊ります", kana: "おどります", no: "å danse" },
  { kanji: "遊びます", kana: "あそびます", no: "å leke / ha det gøy" },
  { kanji: "泊まります", kana: "とまります", no: "å overnatte" },
  { kanji: "乗ります", kana: "のります", no: "å gå på (transport)" },
  { kanji: "降ります", kana: "おります", no: "å gå av (transport)" },
  { kanji: "渡ります", kana: "わたります", no: "å krysse (gate/bro)" },
  { kanji: "曲がります", kana: "まがります", no: "å svinge" },
  { kanji: "止まります", kana: "とまります", no: "å stoppe" },
  { kanji: "送ります", kana: "おくります", no: "å sende" },
  { kanji: null, kana: "もらいます", no: "å få / motta" },
  { kanji: null, kana: "あげます", no: "å gi (bort)" },
  { kanji: null, kana: "くれます", no: "å gi (til meg)" },
  { kanji: "借ります", kana: "かります", no: "å låne (av noen)" },
  { kanji: "貸します", kana: "かします", no: "å låne bort" },
  { kanji: "返します", kana: "かえします", no: "å levere tilbake" },
  { kanji: "忘れます", kana: "わすれます", no: "å glemme" },
  { kanji: "覚えます", kana: "おぼえます", no: "å huske / lære utenat" },
  { kanji: "始まります", kana: "はじまります", no: "å begynne" },
  { kanji: "終わります", kana: "おわります", no: "å slutte / bli ferdig" },
  { kanji: "分かります", kana: "わかります", no: "å forstå" },
  { kanji: "撮ります", kana: "とります", no: "å ta (bilde)" },
  { kanji: "消します", kana: "けします", no: "å slå av / slette" },
  { kanji: null, kana: "つけます", no: "å slå på" },
  { kanji: "急ぎます", kana: "いそぎます", no: "å skynde seg" },
  { kanji: "手伝います", kana: "てつだいます", no: "å hjelpe" },
];
if (typeof module !== "undefined") module.exports = VERBS;
